### ISSUE TITLE
Can you make this app for twitter follow and unfollowing 

### ISSUE THREAD

**Issue by gdafzalkhan99** [AmadeuscyfCao/githubApp#3]
Hi developer,
Can you make this app for twitter follow and unfollowing?

**Comment by AmadeuscyfCao** [comment]
It's possible if twitter has an official API. Currently I am working on other projects and have no time for developing the twitter version. This is just a project for learning android.

**Comment by gdafzalkhan99** [comment]
yes its possible Twitter official API available on twitter developer if you can do?

**Comment by gdafzalkhan99** [comment]
https://play.google.com/store/apps/details?id=follow.unfollow.twitterfollow 

this is an example app available on google play.
